### PR TITLE
#164363488 Delete A Specific Meetup by Id

### PR DESCRIPTION
**Pull request by Amoswachira**
#### What does this PR do?
Deletes a specific meet by id
#### Description of Task to be completed?
* Ensure the following endpoint is working:-
```
1. DELETE /api/meetups/<str:meetupid>
```
### Local Development Setup
 - First Create python virtual env
 ```
  $ virtualenv -p python .venv
 ```
 - Install Requirements
 ```
  $ pip install -r requiremts.txt
 ```
 - Copy .env-example to .env and set config
 ```
  $ cp .env-example .env
 ```
 - Create postgres database
 ```
  $ sudo su postgres
  $ psql
  postgres=# CREATE USER django WITH PASSWORD 'password';
  postgres=# ALTER ROLE django SET client_encoding TO 'utf8';
  postgres=# ALTER ROLE django SET default_transaction_isolation TO 'read committed';
  postgres=# ALTER ROLE django SET timezone TO 'UTC';
  postgres=# CREATE DATABASE drf;
  postgres=# GRANT ALL PRIVILEGES ON DATABASE drf TO django;
  postgres=# \q
  $ exit
````
### Create admin user
Create admin user using your email and password
```
1. cd api/
2. python manage.py createsuperuser
 ```
 - Run Server
 ```
  $ python manage.py runserver
 ```
a. **After cloning the repo:-**
```
git checkout ft-view-meetups-164363505
```
b. **Create meetups**
Follow there instructions [here](https://github.com/Ogutu-Brian/questioners/pull/6) to create meetups 
c. **Test with postman**
Use postman as shown below
1. ***Delete a meet up***
delete

d **Run tests from terminal**
```
1. cd /api/
2. python manage.py test
```
#### What are the relevant pivotal tracker stories?
#164363488

### CODE REVIEW

**Review by matthenge — APPROVED** [review]
Great work @Amoswachira  It works okay

**Review by Ogutu-Brian — COMMENTED** [review]
Good work @Amoswachira

**Review by Ogutu-Brian — APPROVED** [review]
Nice work @Amoswachira

**Review by Bakley — APPROVED** [review]
Good job @Amoswachira . Great work on testing and also testing the 404 error

**Review by a-braham — CHANGES_REQUESTED** [review]
You could add test for deleting a meetup when a person is not authenticated and is not an admin

**Comment by a-braham** [comment]
Otherwise its a great job

**Comment by Amoswachira** [comment]
@a-braham its done

**Review by a-braham — APPROVED** [review]

**Pull request merged**
