### PR TITLE
#164363505 View Meetups endpoints for Questioner App (API)

### PR DESCRIPTION
**Pull request by Ogutu-Brian**
### What does this PR do?
Adds endpoints for viewing meetups
### What are the tasks to be completed?
* Ensure the following endpoints are working:-
```
1. GET /api/meetups/
2. GET /api/meetups/upcoming/
3. GET /api/meetups/<meetup-id>
```
* Ensure the following are achieved:-
```
1. Ensure all specific meetup information are returned by the endpoints
2. Add pagination to GET upcoming meetups endpoint
3. Add pagination to GET all meetups endpoint
```
### Local Development Setup
 - First Create python virtual env
 ```
  $ virtualenv -p python .venv
 ```
 - Install Requirements
 ```
  $ pip install -r requiremts.txt
 ```
 - Copy .env-example to .env and set config
 ```
  $ cp .env-example .env
 ```
 - Create postgres database
 ```
  $ sudo su postgres
  $ psql
  postgres=# CREATE USER django WITH PASSWORD 'password';
  postgres=# ALTER ROLE django SET client_encoding TO 'utf8';
  postgres=# ALTER ROLE django SET default_transaction_isolation TO 'read committed';
  postgres=# ALTER ROLE django SET timezone TO 'UTC';
  postgres=# CREATE DATABASE drf;
  postgres=# GRANT ALL PRIVILEGES ON DATABASE drf TO django;
  postgres=# \q
  $ exit
````
### Create admin user
Create admin user using your email and password
```
1. cd api/
2. python manage.py createsuperuser
 ```
 - Run Server
 ```
  $ python manage.py runserver
 ```
a. **After cloning the repo:-**
```
git checkout ft-view-meetups-164363505
```
b. **Create meetups**
Follow there instructions [here](https://github.com/Ogutu-Brian/questioners/pull/6) to create meetups 
c. **Test with postman**
Use postman as shown below

1. ***All meetups***
Use postman to test as shown below:
Screenshot from 2019-03-14 12-13-31

2. ***Specific meetup***
Get a meetup id from one of the meetups then test with postman as shown below:
`c3c9e8ab-04fa-4669-adb3-ec95a415e135` is the meetup id
Screenshot from 2019-03-14 12-08-13

3. ***Upcoming meetups**
Test with postman as shown below:-
Screenshot from 2019-03-14 12-12-13

***Pagination Screnshots***
Screenshot from 2019-03-14 12-09-35
Screenshot from 2019-03-14 12-10-24

d **Run tests from terminal**
```
1. cd /api/
2. python manage.py test
```
### What are the relevant pivotal tracker stories?
[#164363505](https://www.pivotaltracker.com/story/show/164363505)

### CODE REVIEW

**Review by a-braham — APPROVED** [review]
This looks good to me.

**Comment by Amoswachira** [comment]
nice work on the view meet ups

**Review by Amoswachira — APPROVED** [review]
Everything looks good

**Comment by Philipotieno** [comment]
Looks great @Ogutu-Brian

**Review by IssaIan — APPROVED** [review]
Looks good

**Review by matthenge — APPROVED** [review]
Great work @Ogutu-Brian

**Comment by Ogutu-Brian** [comment]
> Great work @Ogutu-Brian

Great job too @matthenge

**Pull request merged**
