### PR TITLE
#164721952 Return User details instead of user UID when viewing resources(CRUD)

### PR DESCRIPTION
**Pull request by Ogutu-Brian**
### What does this PR do?
Adds User details instead of user UID when viewing resources
## What are the tasks to be completed?
```
1. Ensure all the GET endpoints that return have user id return valid User info.
```
### Local Development Setup
 - First Create python virtual env
 ```
  $ virtualenv -p python .venv
 ```
 - Install Requirements
 ```
  $ pip install -r requiremts.txt
 ```
 - Copy .env-example to .env and set config
 ```
  $ cp .env-example .env
 ```
 - Create postgres database
 ```
  $ sudo su postgres
  $ psql
  postgres=# CREATE USER django WITH PASSWORD 'password';
  postgres=# ALTER ROLE django SET client_encoding TO 'utf8';
  postgres=# ALTER ROLE django SET default_transaction_isolation TO 'read committed';
  postgres=# ALTER ROLE django SET timezone TO 'UTC';
  postgres=# CREATE DATABASE drf;
  postgres=# GRANT ALL PRIVILEGES ON DATABASE drf TO django;
  postgres=# \q
  $ exit
````
### Create admin user
Create admin user using your email and password
```
1. cd api/
2. python manage.py createsuperuser
 ```
 - Run Server
 ```
  $ python manage.py runserver
 ```
a. **After cloning the repo:-**
```
$ git checkout   bg-update-return-resources-164721952
$ cd config/
 replace line 18 in swagger.py file with your local host server
```
b. **Test Endpoints**
```
Check all the endpoints
```
### Screenshots
Screenshot from 2019-03-20 13-54-22
Screenshot from 2019-03-20 13-55-38
Screenshot from 2019-03-20 13-59-33
Screenshot from 2019-03-20 14-02-13

### What are the relevant pivotal tracker stories?
[#164721952](https://www.pivotaltracker.com/story/show/164721952)

### CODE REVIEW

**Review by IssaIan — DISMISSED** [review]
Great work @Ogutu-Brian. The initiative is appreciated.

**Review by a-braham — DISMISSED** [review]

**Review by davenjeru — CHANGES_REQUESTED** [review]
The creator part should be a dictionary having the user's details, for example:

```json
{
   "...some other meetup details" : "...",
   "creator": {
        "name": "Ogutu Brian",
        "nickname": "Ogutu",
        "id": "c5bfe287-e7d1-42c5-b626-8f62afdbc1e2"
   }
}
```

**Comment by Ogutu-Brian** [comment]
> The creator part should be a dictionary having the user's details, for example:
> 
> ```json
> {
>    "...some other meetup details" : "...",
>    "creator": {
>         "name": "Ogutu Brian",
>         "nickname": "Ogutu",
>         "id": "c5bfe287-e7d1-42c5-b626-8f62afdbc1e2"
>    }
> }
> ```

**Comment by Ogutu-Brian** [comment]
> > The creator part should be a dictionary having the user's details, for example:
> > ```json
> > {
> >    "...some other meetup details" : "...",
> >    "creator": {
> >         "name": "Ogutu Brian",
> >         "nickname": "Ogutu",
> >         "id": "c5bfe287-e7d1-42c5-b626-8f62afdbc1e2"
> >    }
> > }
> > ```

Let me fix that @davenjeru

**Comment by Ogutu-Brian** [comment]
> The creator part should be a dictionary having the user's details, for example:
> 
> ```json
> {
>    "...some other meetup details" : "...",
>    "creator": {
>         "name": "Ogutu Brian",
>         "nickname": "Ogutu",
>         "id": "c5bfe287-e7d1-42c5-b626-8f62afdbc1e2"
>    }
> }
> ```

Done @davenjeru ,
Test and let me know if I could make more improvements on it

**Review by Amoswachira — APPROVED** [review]
nice it works

**Review by davenjeru — APPROVED** [review]

**Pull request merged**
