### PR TITLE
#164722064 Consolidate google signup and login urls 

### PR DESCRIPTION
**Pull request by IssaIan**
### What does this PR do?
- Consolidates google signup and login urls 
### Task to be completed
- Change google login and google signup urls to `/api/auth/google/login` and `/api/auth/google/signup` respectively.
- Change the respective urls on swagger documentation
### Relevant Pivotal Tracker Story
[#164722064](https://www.pivotaltracker.com/n/projects/2315729/stories/164722064)

### CODE REVIEW

**Comment by IssaIan** [comment]
@davenjeru this PR should only be merged after reviewing the answer feature as it also contains that feature

**Review by Ogutu-Brian — COMMENTED** [review]
This is a great work @IssaIan ,
However, you could add more detail to the PR e.g the link to the relevant pt story so that one would follow what it tries to accomplish

**Comment by IssaIan** [comment]
> This is a great work @IssaIan ,
> However, you could add more detail to the PR e.g the link to the relevant pt story so that one would follow what it tries to accomplish

Will do so. Thanks.

**Review by Amoswachira — APPROVED** [review]
Nice looks good

**Pull request merged**
