### PR TITLE
#164275574 Adds configurations and settings to deploy to heroku

### PR DESCRIPTION
**Pull request by Philipotieno**
#### What does this PR do?
- Set up and deploy the application on Heroku
#### Description of Task to be completed?
- Set up deployment configurations locally
- Create a pipeline on Heroku
- Deploy the base application and get the respective staging and production urls working
#### How should this be manually tested?
- [Staging](https://questioners-two-staging.herokuapp.com/)
- [Production](https://questioners-pro.herokuapp.com/)
#### Any background context you want to provide?
- One should be able to access live application when he/she navigates to provided URLs in the brows
#### What are the relevant pivotal tracker stories?
[#164275574](https://www.pivotaltracker.com/n/projects/2315729/stories/164275574)
#### Screenshots 

Staging
screenshot from 2019-03-06 01-37-15

Production
screenshot from 2019-03-06 16-42-58

### CODE REVIEW

**Review by Ogutu-Brian — APPROVED** [review]

**Comment by Ogutu-Brian** [comment]
Great job @Philipotieno

**Comment by Philipotieno** [comment]
Thanks @Ogutu-Brian

**Review by IssaIan — APPROVED** [review]
Good job on the deployment. Appreciated how well you handled input provided.

**Review by Ogutu-Brian — CHANGES_REQUESTED** [review]
Hello @Philipotieno ,
Please fix the travis CI build

**Review by Ogutu-Brian — APPROVED** [review]

**Pull request merged**
