### PR TITLE
#164275556 Added swagger documentation to the API

### PR DESCRIPTION
**Pull request by a-braham**
#### What does this PR do?
Setup Swagger documentation so developers can add the documentation of their endpoints.

#### Description of Task to be completed?
Have the following working
`GET api/schema/swagger`

#### How should this be manually tested?
After cloning the repo, cd into questioner
- Activate virtual environment
- RUN `python api/manage.py runserver`
_key_: Use chrome browser to run swagger for better results
- To test the documentation, run the endpoint

#### Any background context you want to provide?
The authentication at this point does not work since the endpoints are not protected. So, the current user is anonymous.
#### What are the relevant pivotal tracker stories?
[#164275556](https://www.pivotaltracker.com/n/projects/2315729/stories/164275556)
#### Screenshots (if appropriate)
swagger

### CODE REVIEW

**Comment by Ogutu-Brian** [comment]
Good job @a-braham , 
However, can you consider removing the section of *Questions* on the PR?, I don't think it is very necessary

**Comment by IssaIan** [comment]
Great worl @a-braham 
Consider explaining how the testing should better. The second line is not clearly understood. Otherwise, looks good!

**Review by IssaIan — COMMENTED** [review]
What is the purpose of the new generated file,  api/users/migrations/0002_auto_20190304_1948.py? 
I see no changes made to the models yet, a new migration?
Please enlighten on this.

**Review by Ogutu-Brian — APPROVED** [review]

**Review by Ogutu-Brian — COMMENTED** [review]
Hello @a-braham ,
Kindly address the review from @IssaIan .

**Review by Bakley — APPROVED** [review]
@Ogutu-Brian and @IssaIan I feel that @a-braham had pushed the `api/users/migrations/0002_auto_20190304_1948.py` file by mistake. I guess our gitignore isn't ignoring the migrations file. I had the same file when I run migration on my local machine
Apart from that, I think @a-braham did a solid job

**Review by matthenge — CHANGES_REQUESTED** [review]
Looks good, however I believe it's good practice to leave a blank line at the end of a page. @a-braham would you consider doing that for the .gitignore file

**Comment by a-braham** [comment]
Sorry guys for not addressing the issues sooner was offline throughout the day

**Comment by a-braham** [comment]
@IssaIan Is it clear now?
@Ogutu-Brian @IssaIan I have removed the file

Thank you all for the review

**Comment by a-braham** [comment]
@matthenge Thanks for the observation

**Review by matthenge — APPROVED** [review]

**Review by IssaIan — APPROVED** [review]

**Review by davenjeru — APPROVED** [review]
LGTM

**Pull request merged**
