### PR TITLE
 #164362051  unit test for change password endpoint

### PR DESCRIPTION
**Pull request by Amoswachira**
#### What does this PR do?
Enables the currently logged in user to change their password
#### Description of Task to be completed?
- Have the following endpoint working If I a user registered an account with basic credentials
```
 Post  /api/auth/change_password/
 ```
-Add unit tests for the change password endpoint
#### How should this be manually tested?
- clone the repo
- Create python virtual env
 ```
  $ virtualenv -p python .venv
 ```
 - Install Requirements
 ```
  $ pip install -r api/requiremts.txt
 ```
 - Copy .env-example to .env and set config
 ```
  $ copy .env-example .env
 ```
 - Copy .env-example to .env and set config-In Ubuntu and Kali linux
 ```
  $ cp .env-example .env
 ```
 
 - Create postgres database
 ```
  $ sudo su postgres
  $ psql
  postgres=# CREATE USER django WITH PASSWORD 'password';
  postgres=# ALTER ROLE django SET client_encoding TO 'utf8';
  postgres=# ALTER ROLE django SET default_transaction_isolation TO 'read committed';
  postgres=# ALTER ROLE django SET timezone TO 'UTC';
  postgres=# CREATE DATABASE drf;
  postgres=# GRANT ALL PRIVILEGES ON DATABASE drf TO django;
  postgres=# \q
  $ exit
 ```
- Git checkout
'''
$git checkout ft-change-password-164362051
'''
 - Run Tests
 ```
  $ python api/manage.py test auth
 ```
 - Run Server
 ```
  $ python api/manage.py runserver
 ```
#### What are the relevant pivotal tracker stories?
#164362051

#### Screenshots (if appropriate)
chnage passwor endpoint 2

### CODE REVIEW

**Review by matthenge — CHANGES_REQUESTED** [review]
Great work @Amoswachira  I have noticed that the tests file does not have a blank line at the end maybe you can consider that so as to conform to pep8 standards

**Review by Ogutu-Brian — COMMENTED** [review]
Hello @Amoswachira ,
Good work. What if you made the tests `DRY`, there is redundancy in redefinition of data
and authorization, you can setup authorized user and valid data in the setUp
then you will just alter values in given tests.

**Comment by Ogutu-Brian** [comment]
> Great work @Amoswachira I have noticed that the tests file does not have a blank line at the end maybe you can consider that so as to conform to pep8 standards

Hello @Amoswachira , 
You can install autopep8, if you are using visual studio code, you can select the whole code in the file then pres `CTR+SHIF+I`. It will do some good formatting for your code and add the new line at the end of file.

**Comment by Amoswachira** [comment]
@Ogutu-Brian @matthenge  All done

**Review by Ogutu-Brian — APPROVED** [review]

**Comment by Amoswachira** [comment]
@matthenge  i have fixed it

**Review by IssaIan — CHANGES_REQUESTED** [review]
Looks good. But we agreed to place the tests in a folder called test containing an __init__.py file and your respective tests to enable easier merging into develop and improve workflow. Check on that.

**Comment by Amoswachira** [comment]
@IssaIan it is fixed

**Review by IssaIan — APPROVED** [review]

**Review by matthenge — APPROVED** [review]

**Pull request merged**
