### PR TITLE
#164822920 Add rsvps to meetups Responses (API)

### PR DESCRIPTION
**Pull request by Ogutu-Brian**
### What does this PR do?
Adds rsvps to meetups responses
### What are the tasks to be completed?
* Ensure the GET endpoints for meetups have their respective rsvps
* Ensure the following endpoint for fetching rsvps on a meetup is added:
```` 
GET /api/meetups/{meetupId}/rsvps
````
### Local Development Setup
 - First Create python virtual env
 ```
  $ virtualenv -p python .venv
 ```
 - Install Requirements
 ```
  $ pip install -r requiremts.txt
 ```
 - Copy .env-example to .env and set config
 ```
  $ cp .env-example .env
 ```
 - Create postgres database
 ```
  $ sudo su postgres
  $ psql
  postgres=# CREATE USER django WITH PASSWORD 'password';
  postgres=# ALTER ROLE django SET client_encoding TO 'utf8';
  postgres=# ALTER ROLE django SET default_transaction_isolation TO 'read committed';
  postgres=# ALTER ROLE django SET timezone TO 'UTC';
  postgres=# CREATE DATABASE drf;
  postgres=# GRANT ALL PRIVILEGES ON DATABASE drf TO django;
  postgres=# \q
  $ exit
````
### Create admin user
Create admin user using your email and password
```
1. cd api/
2. python manage.py createsuperuser
 ```
 - Run Server
 ```
  $ python manage.py runserver
 ```
a. **After cloning the repo:-**
```
$ git checkout  bg-update-meetup-response-164822920
$ cd config/
 - replace line 18 in swagger.py file with your local host server
 - On your web browser, go to your-local-host/api/schema/swagger/
```
b. **Test Endpoints**
1. Follow the procedure [here](https://github.com/Ogutu-Brian/questioners/pull/16) to create rsvps
2. Test GET endpoints in meetups

### Screenshots
Screenshot from 2019-03-26 14-22-06
Screenshot from 2019-03-26 14-28-29
Screenshot from 2019-03-26 14-55-58
Screenshot from 2019-03-26 14-56-13

### What are the relevant pivotal tracker stories?
[#164822920](https://www.pivotaltracker.com/story/show/164822920)

### CODE REVIEW

**Review by Amoswachira — COMMENTED** [review]
@Ogutu-Brian you can edit your PR on this section ```replace line 18 in swagger.py file with your local host server```  to ```change your URL in the SWAGGER_URL variable in the  .env file ``` since @IssaIan has already added  the environmental variable for swagger URL

**Comment by Ogutu-Brian** [comment]
> @Ogutu-Brian you can edit your PR on this section `replace line 18 in swagger.py file with your local host server` to `change your URL in the SWAGGER_URL variable in the .env file ` since @IssaIan has already added the environmental variable for swagger URL

I've done that @Amoswachira ,
More feedback are welcome

**Review by Amoswachira — APPROVED** [review]

**Review by a-braham — APPROVED** [review]

**Comment by davenjeru** [comment]
@Ogutu-Brian, could you add a screenshot to see how the rsvp data looks like?

**Comment by Ogutu-Brian** [comment]
> @Ogutu-Brian, could you add a screenshot to see how the rsvp data looks like?

Hello @davenjeru ,
I have updated it on the initial comment above

**Review by Bakley — APPROVED** [review]
Hey, @Ogutu-Brian Good job done on this. I did test it out using swagger and it meets expectation. When, a user updates the RSVP it also changes the count on the meetup summary. Also, signed up another user and did an RSVP the summary updated as required.

**Pull request merged**
